[2025-05-15T17:06:52.600+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-15T17:06:52.632+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: korzina_parser_dag.parse_korzina scheduled__2025-05-14T08:00:00+00:00 [queued]>
[2025-05-15T17:06:52.640+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: korzina_parser_dag.parse_korzina scheduled__2025-05-14T08:00:00+00:00 [queued]>
[2025-05-15T17:06:52.641+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 5
[2025-05-15T17:06:52.655+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parse_korzina> on 2025-05-14 08:00:00+00:00
[2025-05-15T17:06:52.659+0000] {standard_task_runner.py:63} INFO - Started process 220 to run task
[2025-05-15T17:06:52.662+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'korzina_parser_dag', 'parse_korzina', 'scheduled__2025-05-14T08:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/korzinavdom_dag.py', '--cfg-path', '/tmp/tmpof7hh24x']
[2025-05-15T17:06:52.670+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask parse_korzina
[2025-05-15T17:06:52.721+0000] {task_command.py:426} INFO - Running <TaskInstance: korzina_parser_dag.parse_korzina scheduled__2025-05-14T08:00:00+00:00 [running]> on host b141e5429350
[2025-05-15T17:06:52.818+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='korzina_parser_dag' AIRFLOW_CTX_TASK_ID='parse_korzina' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-14T08:00:00+00:00'
[2025-05-15T17:06:52.819+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-15T17:06:52.833+0000] {parser.py:16} INFO - Начинаем парсинг сайта korzinavdom.kz
[2025-05-15T17:06:52.834+0000] {parser.py:20} INFO - Запрашиваем страницу: https://korzinavdom.kz/catalog?PAGEN_1=1
[2025-05-15T17:06:53.278+0000] {parser.py:31} INFO - Продукты не найдены, завершение парсинга.
[2025-05-15T17:06:53.279+0000] {parser.py:64} INFO - Подключение к ClickHouse...
[2025-05-15T17:06:56.968+0000] {connection.py:411} WARNING - Failed to connect to clickhouse:9000
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 329, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 280, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
[2025-05-15T17:06:56.971+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-15T17:06:56.971+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/parser.py", line 67, in parse_and_insert
    client.execute('''
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 420, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Name or service not known (clickhouse:9000)
[2025-05-15T17:06:56.986+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=korzina_parser_dag, task_id=parse_korzina, execution_date=20250514T080000, start_date=20250515T170652, end_date=20250515T170656
[2025-05-15T17:06:56.999+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task parse_korzina (Code: 210. Name or service not known (clickhouse:9000); 220)
[2025-05-15T17:06:57.011+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-15T17:06:57.030+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T17:06:57.031+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
